# Generated by Django 5.2.3 on 2025-06-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(),
        ),
    ]
