# Generated by Django 5.2.3 on 2025-06-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_alter_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
