# Generated by Django 5.2.3 on 2025-06-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkartapp', '0003_remove_product_category_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='items',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
