# Generated by Django 5.2.3 on 2025-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkartapp', '0008_product_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('skincare', 'Skincare'), ('makeup', 'Makeup'), ('haircare', 'Haircare'), ('fragrance', 'Fragrance'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
